# index:
#    path: /
#    controller: App\Controller\FirstController::index

hello:
    path: /hello-world
    controller: App\Controller\HelloWorldController::helloMessage

hello-view:
    path: /hello-world-view
    controller: App\Controller\HelloWorldController::helloMessageView


# dice:
#     path: /dice
#     controller: App\Controller\DiceController::diceGame
